// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessage.proto

package com.randioo.shanghaimajiang_server.protocol;

public final class ClientMessage {
  private ClientMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class CS extends
      com.google.protobuf.GeneratedMessage {
    // Use CS.newBuilder() to construct.
    private CS() {
      initFields();
    }
    private CS(boolean noInit) {}
    
    private static final CS defaultInstance;
    public static CS getDefaultInstance() {
      return defaultInstance;
    }
    
    public CS getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.shanghaimajiang_server.protocol.ClientMessage.internal_static_com_randioo_shanghaimajiang_server_protocol_CS_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.shanghaimajiang_server.protocol.ClientMessage.internal_static_com_randioo_shanghaimajiang_server_protocol_CS_fieldAccessorTable;
    }
    
    // optional .com.randioo.shanghaimajiang_server.protocol.LoginCheckAccountRequest LoginCheckAccountRequest = 1;
    public static final int LOGINCHECKACCOUNTREQUEST_FIELD_NUMBER = 1;
    private boolean hasLoginCheckAccountRequest;
    private com.randioo.shanghaimajiang_server.protocol.Login.LoginCheckAccountRequest loginCheckAccountRequest_;
    public boolean hasLoginCheckAccountRequest() { return hasLoginCheckAccountRequest; }
    public com.randioo.shanghaimajiang_server.protocol.Login.LoginCheckAccountRequest getLoginCheckAccountRequest() { return loginCheckAccountRequest_; }
    
    // optional .com.randioo.shanghaimajiang_server.protocol.LoginCreateRoleRequest LoginCreateRoleRequest = 2;
    public static final int LOGINCREATEROLEREQUEST_FIELD_NUMBER = 2;
    private boolean hasLoginCreateRoleRequest;
    private com.randioo.shanghaimajiang_server.protocol.Login.LoginCreateRoleRequest loginCreateRoleRequest_;
    public boolean hasLoginCreateRoleRequest() { return hasLoginCreateRoleRequest; }
    public com.randioo.shanghaimajiang_server.protocol.Login.LoginCreateRoleRequest getLoginCreateRoleRequest() { return loginCreateRoleRequest_; }
    
    // optional .com.randioo.shanghaimajiang_server.protocol.LoginGetRoleDataRequest LoginGetRoleDataRequest = 3;
    public static final int LOGINGETROLEDATAREQUEST_FIELD_NUMBER = 3;
    private boolean hasLoginGetRoleDataRequest;
    private com.randioo.shanghaimajiang_server.protocol.Login.LoginGetRoleDataRequest loginGetRoleDataRequest_;
    public boolean hasLoginGetRoleDataRequest() { return hasLoginGetRoleDataRequest; }
    public com.randioo.shanghaimajiang_server.protocol.Login.LoginGetRoleDataRequest getLoginGetRoleDataRequest() { return loginGetRoleDataRequest_; }
    
    // optional .com.randioo.shanghaimajiang_server.protocol.RoleRenameRequest RoleRenameRequest = 4;
    public static final int ROLERENAMEREQUEST_FIELD_NUMBER = 4;
    private boolean hasRoleRenameRequest;
    private com.randioo.shanghaimajiang_server.protocol.Role.RoleRenameRequest roleRenameRequest_;
    public boolean hasRoleRenameRequest() { return hasRoleRenameRequest; }
    public com.randioo.shanghaimajiang_server.protocol.Role.RoleRenameRequest getRoleRenameRequest() { return roleRenameRequest_; }
    
    // optional .com.randioo.shanghaimajiang_server.protocol.MatchNewGameRequest MatchNewGameRequest = 5;
    public static final int MATCHNEWGAMEREQUEST_FIELD_NUMBER = 5;
    private boolean hasMatchNewGameRequest;
    private com.randioo.shanghaimajiang_server.protocol.Match.MatchNewGameRequest matchNewGameRequest_;
    public boolean hasMatchNewGameRequest() { return hasMatchNewGameRequest; }
    public com.randioo.shanghaimajiang_server.protocol.Match.MatchNewGameRequest getMatchNewGameRequest() { return matchNewGameRequest_; }
    
    // optional .com.randioo.shanghaimajiang_server.protocol.MatchJoinGameRequest MatchJoinGameRequest = 6;
    public static final int MATCHJOINGAMEREQUEST_FIELD_NUMBER = 6;
    private boolean hasMatchJoinGameRequest;
    private com.randioo.shanghaimajiang_server.protocol.Match.MatchJoinGameRequest matchJoinGameRequest_;
    public boolean hasMatchJoinGameRequest() { return hasMatchJoinGameRequest; }
    public com.randioo.shanghaimajiang_server.protocol.Match.MatchJoinGameRequest getMatchJoinGameRequest() { return matchJoinGameRequest_; }
    
    // optional .com.randioo.shanghaimajiang_server.protocol.FightCmdRequest FightCmdRequest = 7;
    public static final int FIGHTCMDREQUEST_FIELD_NUMBER = 7;
    private boolean hasFightCmdRequest;
    private com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest fightCmdRequest_;
    public boolean hasFightCmdRequest() { return hasFightCmdRequest; }
    public com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest getFightCmdRequest() { return fightCmdRequest_; }
    
    private void initFields() {
      loginCheckAccountRequest_ = com.randioo.shanghaimajiang_server.protocol.Login.LoginCheckAccountRequest.getDefaultInstance();
      loginCreateRoleRequest_ = com.randioo.shanghaimajiang_server.protocol.Login.LoginCreateRoleRequest.getDefaultInstance();
      loginGetRoleDataRequest_ = com.randioo.shanghaimajiang_server.protocol.Login.LoginGetRoleDataRequest.getDefaultInstance();
      roleRenameRequest_ = com.randioo.shanghaimajiang_server.protocol.Role.RoleRenameRequest.getDefaultInstance();
      matchNewGameRequest_ = com.randioo.shanghaimajiang_server.protocol.Match.MatchNewGameRequest.getDefaultInstance();
      matchJoinGameRequest_ = com.randioo.shanghaimajiang_server.protocol.Match.MatchJoinGameRequest.getDefaultInstance();
      fightCmdRequest_ = com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasLoginCheckAccountRequest()) {
        output.writeMessage(1, getLoginCheckAccountRequest());
      }
      if (hasLoginCreateRoleRequest()) {
        output.writeMessage(2, getLoginCreateRoleRequest());
      }
      if (hasLoginGetRoleDataRequest()) {
        output.writeMessage(3, getLoginGetRoleDataRequest());
      }
      if (hasRoleRenameRequest()) {
        output.writeMessage(4, getRoleRenameRequest());
      }
      if (hasMatchNewGameRequest()) {
        output.writeMessage(5, getMatchNewGameRequest());
      }
      if (hasMatchJoinGameRequest()) {
        output.writeMessage(6, getMatchJoinGameRequest());
      }
      if (hasFightCmdRequest()) {
        output.writeMessage(7, getFightCmdRequest());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasLoginCheckAccountRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getLoginCheckAccountRequest());
      }
      if (hasLoginCreateRoleRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getLoginCreateRoleRequest());
      }
      if (hasLoginGetRoleDataRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getLoginGetRoleDataRequest());
      }
      if (hasRoleRenameRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getRoleRenameRequest());
      }
      if (hasMatchNewGameRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getMatchNewGameRequest());
      }
      if (hasMatchJoinGameRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getMatchJoinGameRequest());
      }
      if (hasFightCmdRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getFightCmdRequest());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.shanghaimajiang_server.protocol.ClientMessage.CS parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.ClientMessage.CS parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.ClientMessage.CS parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.ClientMessage.CS parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.ClientMessage.CS parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.ClientMessage.CS parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.ClientMessage.CS parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shanghaimajiang_server.protocol.ClientMessage.CS parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shanghaimajiang_server.protocol.ClientMessage.CS parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.ClientMessage.CS parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.shanghaimajiang_server.protocol.ClientMessage.CS prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.shanghaimajiang_server.protocol.ClientMessage.CS result;
      
      // Construct using com.randioo.shanghaimajiang_server.protocol.ClientMessage.CS.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.shanghaimajiang_server.protocol.ClientMessage.CS();
        return builder;
      }
      
      protected com.randioo.shanghaimajiang_server.protocol.ClientMessage.CS internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.shanghaimajiang_server.protocol.ClientMessage.CS();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.shanghaimajiang_server.protocol.ClientMessage.CS.getDescriptor();
      }
      
      public com.randioo.shanghaimajiang_server.protocol.ClientMessage.CS getDefaultInstanceForType() {
        return com.randioo.shanghaimajiang_server.protocol.ClientMessage.CS.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.shanghaimajiang_server.protocol.ClientMessage.CS build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.shanghaimajiang_server.protocol.ClientMessage.CS buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.shanghaimajiang_server.protocol.ClientMessage.CS buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.shanghaimajiang_server.protocol.ClientMessage.CS returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.shanghaimajiang_server.protocol.ClientMessage.CS) {
          return mergeFrom((com.randioo.shanghaimajiang_server.protocol.ClientMessage.CS)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.shanghaimajiang_server.protocol.ClientMessage.CS other) {
        if (other == com.randioo.shanghaimajiang_server.protocol.ClientMessage.CS.getDefaultInstance()) return this;
        if (other.hasLoginCheckAccountRequest()) {
          mergeLoginCheckAccountRequest(other.getLoginCheckAccountRequest());
        }
        if (other.hasLoginCreateRoleRequest()) {
          mergeLoginCreateRoleRequest(other.getLoginCreateRoleRequest());
        }
        if (other.hasLoginGetRoleDataRequest()) {
          mergeLoginGetRoleDataRequest(other.getLoginGetRoleDataRequest());
        }
        if (other.hasRoleRenameRequest()) {
          mergeRoleRenameRequest(other.getRoleRenameRequest());
        }
        if (other.hasMatchNewGameRequest()) {
          mergeMatchNewGameRequest(other.getMatchNewGameRequest());
        }
        if (other.hasMatchJoinGameRequest()) {
          mergeMatchJoinGameRequest(other.getMatchJoinGameRequest());
        }
        if (other.hasFightCmdRequest()) {
          mergeFightCmdRequest(other.getFightCmdRequest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.randioo.shanghaimajiang_server.protocol.Login.LoginCheckAccountRequest.Builder subBuilder = com.randioo.shanghaimajiang_server.protocol.Login.LoginCheckAccountRequest.newBuilder();
              if (hasLoginCheckAccountRequest()) {
                subBuilder.mergeFrom(getLoginCheckAccountRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginCheckAccountRequest(subBuilder.buildPartial());
              break;
            }
            case 18: {
              com.randioo.shanghaimajiang_server.protocol.Login.LoginCreateRoleRequest.Builder subBuilder = com.randioo.shanghaimajiang_server.protocol.Login.LoginCreateRoleRequest.newBuilder();
              if (hasLoginCreateRoleRequest()) {
                subBuilder.mergeFrom(getLoginCreateRoleRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginCreateRoleRequest(subBuilder.buildPartial());
              break;
            }
            case 26: {
              com.randioo.shanghaimajiang_server.protocol.Login.LoginGetRoleDataRequest.Builder subBuilder = com.randioo.shanghaimajiang_server.protocol.Login.LoginGetRoleDataRequest.newBuilder();
              if (hasLoginGetRoleDataRequest()) {
                subBuilder.mergeFrom(getLoginGetRoleDataRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginGetRoleDataRequest(subBuilder.buildPartial());
              break;
            }
            case 34: {
              com.randioo.shanghaimajiang_server.protocol.Role.RoleRenameRequest.Builder subBuilder = com.randioo.shanghaimajiang_server.protocol.Role.RoleRenameRequest.newBuilder();
              if (hasRoleRenameRequest()) {
                subBuilder.mergeFrom(getRoleRenameRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setRoleRenameRequest(subBuilder.buildPartial());
              break;
            }
            case 42: {
              com.randioo.shanghaimajiang_server.protocol.Match.MatchNewGameRequest.Builder subBuilder = com.randioo.shanghaimajiang_server.protocol.Match.MatchNewGameRequest.newBuilder();
              if (hasMatchNewGameRequest()) {
                subBuilder.mergeFrom(getMatchNewGameRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMatchNewGameRequest(subBuilder.buildPartial());
              break;
            }
            case 50: {
              com.randioo.shanghaimajiang_server.protocol.Match.MatchJoinGameRequest.Builder subBuilder = com.randioo.shanghaimajiang_server.protocol.Match.MatchJoinGameRequest.newBuilder();
              if (hasMatchJoinGameRequest()) {
                subBuilder.mergeFrom(getMatchJoinGameRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMatchJoinGameRequest(subBuilder.buildPartial());
              break;
            }
            case 58: {
              com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest.Builder subBuilder = com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest.newBuilder();
              if (hasFightCmdRequest()) {
                subBuilder.mergeFrom(getFightCmdRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setFightCmdRequest(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .com.randioo.shanghaimajiang_server.protocol.LoginCheckAccountRequest LoginCheckAccountRequest = 1;
      public boolean hasLoginCheckAccountRequest() {
        return result.hasLoginCheckAccountRequest();
      }
      public com.randioo.shanghaimajiang_server.protocol.Login.LoginCheckAccountRequest getLoginCheckAccountRequest() {
        return result.getLoginCheckAccountRequest();
      }
      public Builder setLoginCheckAccountRequest(com.randioo.shanghaimajiang_server.protocol.Login.LoginCheckAccountRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginCheckAccountRequest = true;
        result.loginCheckAccountRequest_ = value;
        return this;
      }
      public Builder setLoginCheckAccountRequest(com.randioo.shanghaimajiang_server.protocol.Login.LoginCheckAccountRequest.Builder builderForValue) {
        result.hasLoginCheckAccountRequest = true;
        result.loginCheckAccountRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginCheckAccountRequest(com.randioo.shanghaimajiang_server.protocol.Login.LoginCheckAccountRequest value) {
        if (result.hasLoginCheckAccountRequest() &&
            result.loginCheckAccountRequest_ != com.randioo.shanghaimajiang_server.protocol.Login.LoginCheckAccountRequest.getDefaultInstance()) {
          result.loginCheckAccountRequest_ =
            com.randioo.shanghaimajiang_server.protocol.Login.LoginCheckAccountRequest.newBuilder(result.loginCheckAccountRequest_).mergeFrom(value).buildPartial();
        } else {
          result.loginCheckAccountRequest_ = value;
        }
        result.hasLoginCheckAccountRequest = true;
        return this;
      }
      public Builder clearLoginCheckAccountRequest() {
        result.hasLoginCheckAccountRequest = false;
        result.loginCheckAccountRequest_ = com.randioo.shanghaimajiang_server.protocol.Login.LoginCheckAccountRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.shanghaimajiang_server.protocol.LoginCreateRoleRequest LoginCreateRoleRequest = 2;
      public boolean hasLoginCreateRoleRequest() {
        return result.hasLoginCreateRoleRequest();
      }
      public com.randioo.shanghaimajiang_server.protocol.Login.LoginCreateRoleRequest getLoginCreateRoleRequest() {
        return result.getLoginCreateRoleRequest();
      }
      public Builder setLoginCreateRoleRequest(com.randioo.shanghaimajiang_server.protocol.Login.LoginCreateRoleRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginCreateRoleRequest = true;
        result.loginCreateRoleRequest_ = value;
        return this;
      }
      public Builder setLoginCreateRoleRequest(com.randioo.shanghaimajiang_server.protocol.Login.LoginCreateRoleRequest.Builder builderForValue) {
        result.hasLoginCreateRoleRequest = true;
        result.loginCreateRoleRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginCreateRoleRequest(com.randioo.shanghaimajiang_server.protocol.Login.LoginCreateRoleRequest value) {
        if (result.hasLoginCreateRoleRequest() &&
            result.loginCreateRoleRequest_ != com.randioo.shanghaimajiang_server.protocol.Login.LoginCreateRoleRequest.getDefaultInstance()) {
          result.loginCreateRoleRequest_ =
            com.randioo.shanghaimajiang_server.protocol.Login.LoginCreateRoleRequest.newBuilder(result.loginCreateRoleRequest_).mergeFrom(value).buildPartial();
        } else {
          result.loginCreateRoleRequest_ = value;
        }
        result.hasLoginCreateRoleRequest = true;
        return this;
      }
      public Builder clearLoginCreateRoleRequest() {
        result.hasLoginCreateRoleRequest = false;
        result.loginCreateRoleRequest_ = com.randioo.shanghaimajiang_server.protocol.Login.LoginCreateRoleRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.shanghaimajiang_server.protocol.LoginGetRoleDataRequest LoginGetRoleDataRequest = 3;
      public boolean hasLoginGetRoleDataRequest() {
        return result.hasLoginGetRoleDataRequest();
      }
      public com.randioo.shanghaimajiang_server.protocol.Login.LoginGetRoleDataRequest getLoginGetRoleDataRequest() {
        return result.getLoginGetRoleDataRequest();
      }
      public Builder setLoginGetRoleDataRequest(com.randioo.shanghaimajiang_server.protocol.Login.LoginGetRoleDataRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginGetRoleDataRequest = true;
        result.loginGetRoleDataRequest_ = value;
        return this;
      }
      public Builder setLoginGetRoleDataRequest(com.randioo.shanghaimajiang_server.protocol.Login.LoginGetRoleDataRequest.Builder builderForValue) {
        result.hasLoginGetRoleDataRequest = true;
        result.loginGetRoleDataRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginGetRoleDataRequest(com.randioo.shanghaimajiang_server.protocol.Login.LoginGetRoleDataRequest value) {
        if (result.hasLoginGetRoleDataRequest() &&
            result.loginGetRoleDataRequest_ != com.randioo.shanghaimajiang_server.protocol.Login.LoginGetRoleDataRequest.getDefaultInstance()) {
          result.loginGetRoleDataRequest_ =
            com.randioo.shanghaimajiang_server.protocol.Login.LoginGetRoleDataRequest.newBuilder(result.loginGetRoleDataRequest_).mergeFrom(value).buildPartial();
        } else {
          result.loginGetRoleDataRequest_ = value;
        }
        result.hasLoginGetRoleDataRequest = true;
        return this;
      }
      public Builder clearLoginGetRoleDataRequest() {
        result.hasLoginGetRoleDataRequest = false;
        result.loginGetRoleDataRequest_ = com.randioo.shanghaimajiang_server.protocol.Login.LoginGetRoleDataRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.shanghaimajiang_server.protocol.RoleRenameRequest RoleRenameRequest = 4;
      public boolean hasRoleRenameRequest() {
        return result.hasRoleRenameRequest();
      }
      public com.randioo.shanghaimajiang_server.protocol.Role.RoleRenameRequest getRoleRenameRequest() {
        return result.getRoleRenameRequest();
      }
      public Builder setRoleRenameRequest(com.randioo.shanghaimajiang_server.protocol.Role.RoleRenameRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasRoleRenameRequest = true;
        result.roleRenameRequest_ = value;
        return this;
      }
      public Builder setRoleRenameRequest(com.randioo.shanghaimajiang_server.protocol.Role.RoleRenameRequest.Builder builderForValue) {
        result.hasRoleRenameRequest = true;
        result.roleRenameRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeRoleRenameRequest(com.randioo.shanghaimajiang_server.protocol.Role.RoleRenameRequest value) {
        if (result.hasRoleRenameRequest() &&
            result.roleRenameRequest_ != com.randioo.shanghaimajiang_server.protocol.Role.RoleRenameRequest.getDefaultInstance()) {
          result.roleRenameRequest_ =
            com.randioo.shanghaimajiang_server.protocol.Role.RoleRenameRequest.newBuilder(result.roleRenameRequest_).mergeFrom(value).buildPartial();
        } else {
          result.roleRenameRequest_ = value;
        }
        result.hasRoleRenameRequest = true;
        return this;
      }
      public Builder clearRoleRenameRequest() {
        result.hasRoleRenameRequest = false;
        result.roleRenameRequest_ = com.randioo.shanghaimajiang_server.protocol.Role.RoleRenameRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.shanghaimajiang_server.protocol.MatchNewGameRequest MatchNewGameRequest = 5;
      public boolean hasMatchNewGameRequest() {
        return result.hasMatchNewGameRequest();
      }
      public com.randioo.shanghaimajiang_server.protocol.Match.MatchNewGameRequest getMatchNewGameRequest() {
        return result.getMatchNewGameRequest();
      }
      public Builder setMatchNewGameRequest(com.randioo.shanghaimajiang_server.protocol.Match.MatchNewGameRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasMatchNewGameRequest = true;
        result.matchNewGameRequest_ = value;
        return this;
      }
      public Builder setMatchNewGameRequest(com.randioo.shanghaimajiang_server.protocol.Match.MatchNewGameRequest.Builder builderForValue) {
        result.hasMatchNewGameRequest = true;
        result.matchNewGameRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeMatchNewGameRequest(com.randioo.shanghaimajiang_server.protocol.Match.MatchNewGameRequest value) {
        if (result.hasMatchNewGameRequest() &&
            result.matchNewGameRequest_ != com.randioo.shanghaimajiang_server.protocol.Match.MatchNewGameRequest.getDefaultInstance()) {
          result.matchNewGameRequest_ =
            com.randioo.shanghaimajiang_server.protocol.Match.MatchNewGameRequest.newBuilder(result.matchNewGameRequest_).mergeFrom(value).buildPartial();
        } else {
          result.matchNewGameRequest_ = value;
        }
        result.hasMatchNewGameRequest = true;
        return this;
      }
      public Builder clearMatchNewGameRequest() {
        result.hasMatchNewGameRequest = false;
        result.matchNewGameRequest_ = com.randioo.shanghaimajiang_server.protocol.Match.MatchNewGameRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.shanghaimajiang_server.protocol.MatchJoinGameRequest MatchJoinGameRequest = 6;
      public boolean hasMatchJoinGameRequest() {
        return result.hasMatchJoinGameRequest();
      }
      public com.randioo.shanghaimajiang_server.protocol.Match.MatchJoinGameRequest getMatchJoinGameRequest() {
        return result.getMatchJoinGameRequest();
      }
      public Builder setMatchJoinGameRequest(com.randioo.shanghaimajiang_server.protocol.Match.MatchJoinGameRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasMatchJoinGameRequest = true;
        result.matchJoinGameRequest_ = value;
        return this;
      }
      public Builder setMatchJoinGameRequest(com.randioo.shanghaimajiang_server.protocol.Match.MatchJoinGameRequest.Builder builderForValue) {
        result.hasMatchJoinGameRequest = true;
        result.matchJoinGameRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeMatchJoinGameRequest(com.randioo.shanghaimajiang_server.protocol.Match.MatchJoinGameRequest value) {
        if (result.hasMatchJoinGameRequest() &&
            result.matchJoinGameRequest_ != com.randioo.shanghaimajiang_server.protocol.Match.MatchJoinGameRequest.getDefaultInstance()) {
          result.matchJoinGameRequest_ =
            com.randioo.shanghaimajiang_server.protocol.Match.MatchJoinGameRequest.newBuilder(result.matchJoinGameRequest_).mergeFrom(value).buildPartial();
        } else {
          result.matchJoinGameRequest_ = value;
        }
        result.hasMatchJoinGameRequest = true;
        return this;
      }
      public Builder clearMatchJoinGameRequest() {
        result.hasMatchJoinGameRequest = false;
        result.matchJoinGameRequest_ = com.randioo.shanghaimajiang_server.protocol.Match.MatchJoinGameRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.shanghaimajiang_server.protocol.FightCmdRequest FightCmdRequest = 7;
      public boolean hasFightCmdRequest() {
        return result.hasFightCmdRequest();
      }
      public com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest getFightCmdRequest() {
        return result.getFightCmdRequest();
      }
      public Builder setFightCmdRequest(com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasFightCmdRequest = true;
        result.fightCmdRequest_ = value;
        return this;
      }
      public Builder setFightCmdRequest(com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest.Builder builderForValue) {
        result.hasFightCmdRequest = true;
        result.fightCmdRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeFightCmdRequest(com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest value) {
        if (result.hasFightCmdRequest() &&
            result.fightCmdRequest_ != com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest.getDefaultInstance()) {
          result.fightCmdRequest_ =
            com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest.newBuilder(result.fightCmdRequest_).mergeFrom(value).buildPartial();
        } else {
          result.fightCmdRequest_ = value;
        }
        result.hasFightCmdRequest = true;
        return this;
      }
      public Builder clearFightCmdRequest() {
        result.hasFightCmdRequest = false;
        result.fightCmdRequest_ = com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.shanghaimajiang_server.protocol.CS)
    }
    
    static {
      defaultInstance = new CS(true);
      com.randioo.shanghaimajiang_server.protocol.ClientMessage.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.shanghaimajiang_server.protocol.CS)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_shanghaimajiang_server_protocol_CS_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_shanghaimajiang_server_protocol_CS_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ClientMessage.proto\022+com.randioo.shang" +
      "haimajiang_server.protocol\032\013Login.proto\032" +
      "\nRole.proto\032\013Match.proto\032\013Fight.proto\"\253\005" +
      "\n\002CS\022g\n\030LoginCheckAccountRequest\030\001 \001(\0132E" +
      ".com.randioo.shanghaimajiang_server.prot" +
      "ocol.LoginCheckAccountRequest\022c\n\026LoginCr" +
      "eateRoleRequest\030\002 \001(\0132C.com.randioo.shan" +
      "ghaimajiang_server.protocol.LoginCreateR" +
      "oleRequest\022e\n\027LoginGetRoleDataRequest\030\003 " +
      "\001(\0132D.com.randioo.shanghaimajiang_server",
      ".protocol.LoginGetRoleDataRequest\022Y\n\021Rol" +
      "eRenameRequest\030\004 \001(\0132>.com.randioo.shang" +
      "haimajiang_server.protocol.RoleRenameReq" +
      "uest\022]\n\023MatchNewGameRequest\030\005 \001(\0132@.com." +
      "randioo.shanghaimajiang_server.protocol." +
      "MatchNewGameRequest\022_\n\024MatchJoinGameRequ" +
      "est\030\006 \001(\0132A.com.randioo.shanghaimajiang_" +
      "server.protocol.MatchJoinGameRequest\022U\n\017" +
      "FightCmdRequest\030\007 \001(\0132<.com.randioo.shan" +
      "ghaimajiang_server.protocol.FightCmdRequ",
      "est"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_shanghaimajiang_server_protocol_CS_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_shanghaimajiang_server_protocol_CS_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_shanghaimajiang_server_protocol_CS_descriptor,
              new java.lang.String[] { "LoginCheckAccountRequest", "LoginCreateRoleRequest", "LoginGetRoleDataRequest", "RoleRenameRequest", "MatchNewGameRequest", "MatchJoinGameRequest", "FightCmdRequest", },
              com.randioo.shanghaimajiang_server.protocol.ClientMessage.CS.class,
              com.randioo.shanghaimajiang_server.protocol.ClientMessage.CS.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.shanghaimajiang_server.protocol.Login.getDescriptor(),
          com.randioo.shanghaimajiang_server.protocol.Role.getDescriptor(),
          com.randioo.shanghaimajiang_server.protocol.Match.getDescriptor(),
          com.randioo.shanghaimajiang_server.protocol.Fight.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
