// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Entity.proto

package com.randioo.shanghaimajiang_server.protocol;

public final class Entity {
  private Entity() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum GameType
      implements com.google.protobuf.ProtocolMessageEnum {
    GAME_TYPE_YINSANZUI(0, 0),
    GAME_TYPE_KOUDIAN(1, 1),
    GAME_TYPE_QIAOMA(2, 2),
    GAME_TYPE_QINGHUNPENG(3, 3),
    ;
    
    
    public final int getNumber() { return value; }
    
    public static GameType valueOf(int value) {
      switch (value) {
        case 0: return GAME_TYPE_YINSANZUI;
        case 1: return GAME_TYPE_KOUDIAN;
        case 2: return GAME_TYPE_QIAOMA;
        case 3: return GAME_TYPE_QINGHUNPENG;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<GameType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<GameType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<GameType>() {
            public GameType findValueByNumber(int number) {
              return GameType.valueOf(number)
    ;        }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.randioo.shanghaimajiang_server.protocol.Entity.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final GameType[] VALUES = {
      GAME_TYPE_YINSANZUI, GAME_TYPE_KOUDIAN, GAME_TYPE_QIAOMA, GAME_TYPE_QINGHUNPENG, 
    };
    public static GameType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    private final int index;
    private final int value;
    private GameType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    static {
      com.randioo.shanghaimajiang_server.protocol.Entity.getDescriptor();
    }
    
    // @@protoc_insertion_point(enum_scope:com.randioo.shanghaimajiang_server.protocol.GameType)
  }
  
  public static final class RoleData extends
      com.google.protobuf.GeneratedMessage {
    // Use RoleData.newBuilder() to construct.
    private RoleData() {
      initFields();
    }
    private RoleData(boolean noInit) {}
    
    private static final RoleData defaultInstance;
    public static RoleData getDefaultInstance() {
      return defaultInstance;
    }
    
    public RoleData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.shanghaimajiang_server.protocol.Entity.internal_static_com_randioo_shanghaimajiang_server_protocol_RoleData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.shanghaimajiang_server.protocol.Entity.internal_static_com_randioo_shanghaimajiang_server_protocol_RoleData_fieldAccessorTable;
    }
    
    // optional int32 roleId = 1;
    public static final int ROLEID_FIELD_NUMBER = 1;
    private boolean hasRoleId;
    private int roleId_ = 0;
    public boolean hasRoleId() { return hasRoleId; }
    public int getRoleId() { return roleId_; }
    
    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasRoleId()) {
        output.writeInt32(1, getRoleId());
      }
      if (hasName()) {
        output.writeString(2, getName());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasRoleId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getRoleId());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.shanghaimajiang_server.protocol.Entity.RoleData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Entity.RoleData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Entity.RoleData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Entity.RoleData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Entity.RoleData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Entity.RoleData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Entity.RoleData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shanghaimajiang_server.protocol.Entity.RoleData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shanghaimajiang_server.protocol.Entity.RoleData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Entity.RoleData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.shanghaimajiang_server.protocol.Entity.RoleData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.shanghaimajiang_server.protocol.Entity.RoleData result;
      
      // Construct using com.randioo.shanghaimajiang_server.protocol.Entity.RoleData.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.shanghaimajiang_server.protocol.Entity.RoleData();
        return builder;
      }
      
      protected com.randioo.shanghaimajiang_server.protocol.Entity.RoleData internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.shanghaimajiang_server.protocol.Entity.RoleData();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.shanghaimajiang_server.protocol.Entity.RoleData.getDescriptor();
      }
      
      public com.randioo.shanghaimajiang_server.protocol.Entity.RoleData getDefaultInstanceForType() {
        return com.randioo.shanghaimajiang_server.protocol.Entity.RoleData.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.shanghaimajiang_server.protocol.Entity.RoleData build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.shanghaimajiang_server.protocol.Entity.RoleData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.shanghaimajiang_server.protocol.Entity.RoleData buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.shanghaimajiang_server.protocol.Entity.RoleData returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.shanghaimajiang_server.protocol.Entity.RoleData) {
          return mergeFrom((com.randioo.shanghaimajiang_server.protocol.Entity.RoleData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.shanghaimajiang_server.protocol.Entity.RoleData other) {
        if (other == com.randioo.shanghaimajiang_server.protocol.Entity.RoleData.getDefaultInstance()) return this;
        if (other.hasRoleId()) {
          setRoleId(other.getRoleId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setRoleId(input.readInt32());
              break;
            }
            case 18: {
              setName(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional int32 roleId = 1;
      public boolean hasRoleId() {
        return result.hasRoleId();
      }
      public int getRoleId() {
        return result.getRoleId();
      }
      public Builder setRoleId(int value) {
        result.hasRoleId = true;
        result.roleId_ = value;
        return this;
      }
      public Builder clearRoleId() {
        result.hasRoleId = false;
        result.roleId_ = 0;
        return this;
      }
      
      // optional string name = 2;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.shanghaimajiang_server.protocol.RoleData)
    }
    
    static {
      defaultInstance = new RoleData(true);
      com.randioo.shanghaimajiang_server.protocol.Entity.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.shanghaimajiang_server.protocol.RoleData)
  }
  
  public static final class NewGameConfigData extends
      com.google.protobuf.GeneratedMessage {
    // Use NewGameConfigData.newBuilder() to construct.
    private NewGameConfigData() {
      initFields();
    }
    private NewGameConfigData(boolean noInit) {}
    
    private static final NewGameConfigData defaultInstance;
    public static NewGameConfigData getDefaultInstance() {
      return defaultInstance;
    }
    
    public NewGameConfigData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.shanghaimajiang_server.protocol.Entity.internal_static_com_randioo_shanghaimajiang_server_protocol_NewGameConfigData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.shanghaimajiang_server.protocol.Entity.internal_static_com_randioo_shanghaimajiang_server_protocol_NewGameConfigData_fieldAccessorTable;
    }
    
    // optional int32 round = 1;
    public static final int ROUND_FIELD_NUMBER = 1;
    private boolean hasRound;
    private int round_ = 0;
    public boolean hasRound() { return hasRound; }
    public int getRound() { return round_; }
    
    // optional bool bySelfy = 2;
    public static final int BYSELFY_FIELD_NUMBER = 2;
    private boolean hasBySelfy;
    private boolean bySelfy_ = false;
    public boolean hasBySelfy() { return hasBySelfy; }
    public boolean getBySelfy() { return bySelfy_; }
    
    // optional bool laizi = 3;
    public static final int LAIZI_FIELD_NUMBER = 3;
    private boolean hasLaizi;
    private boolean laizi_ = false;
    public boolean hasLaizi() { return hasLaizi; }
    public boolean getLaizi() { return laizi_; }
    
    // optional bool useDouble = 4;
    public static final int USEDOUBLE_FIELD_NUMBER = 4;
    private boolean hasUseDouble;
    private boolean useDouble_ = false;
    public boolean hasUseDouble() { return hasUseDouble; }
    public boolean getUseDouble() { return useDouble_; }
    
    // optional int32 targetRound = 5;
    public static final int TARGETROUND_FIELD_NUMBER = 5;
    private boolean hasTargetRound;
    private int targetRound_ = 0;
    public boolean hasTargetRound() { return hasTargetRound; }
    public int getTargetRound() { return targetRound_; }
    
    // optional .com.randioo.shanghaimajiang_server.protocol.GameType gameType = 6;
    public static final int GAMETYPE_FIELD_NUMBER = 6;
    private boolean hasGameType;
    private com.randioo.shanghaimajiang_server.protocol.Entity.GameType gameType_;
    public boolean hasGameType() { return hasGameType; }
    public com.randioo.shanghaimajiang_server.protocol.Entity.GameType getGameType() { return gameType_; }
    
    // optional bool leizi = 7;
    public static final int LEIZI_FIELD_NUMBER = 7;
    private boolean hasLeizi;
    private boolean leizi_ = false;
    public boolean hasLeizi() { return hasLeizi; }
    public boolean getLeizi() { return leizi_; }
    
    // optional bool huangfan = 8;
    public static final int HUANGFAN_FIELD_NUMBER = 8;
    private boolean hasHuangfan;
    private boolean huangfan_ = false;
    public boolean hasHuangfan() { return hasHuangfan; }
    public boolean getHuangfan() { return huangfan_; }
    
    // optional int32 di = 9;
    public static final int DI_FIELD_NUMBER = 9;
    private boolean hasDi;
    private int di_ = 0;
    public boolean hasDi() { return hasDi; }
    public int getDi() { return di_; }
    
    // optional bool fly = 10;
    public static final int FLY_FIELD_NUMBER = 10;
    private boolean hasFly;
    private boolean fly_ = false;
    public boolean hasFly() { return hasFly; }
    public boolean getFly() { return fly_; }
    
    private void initFields() {
      gameType_ = com.randioo.shanghaimajiang_server.protocol.Entity.GameType.GAME_TYPE_YINSANZUI;
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasRound()) {
        output.writeInt32(1, getRound());
      }
      if (hasBySelfy()) {
        output.writeBool(2, getBySelfy());
      }
      if (hasLaizi()) {
        output.writeBool(3, getLaizi());
      }
      if (hasUseDouble()) {
        output.writeBool(4, getUseDouble());
      }
      if (hasTargetRound()) {
        output.writeInt32(5, getTargetRound());
      }
      if (hasGameType()) {
        output.writeEnum(6, getGameType().getNumber());
      }
      if (hasLeizi()) {
        output.writeBool(7, getLeizi());
      }
      if (hasHuangfan()) {
        output.writeBool(8, getHuangfan());
      }
      if (hasDi()) {
        output.writeInt32(9, getDi());
      }
      if (hasFly()) {
        output.writeBool(10, getFly());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasRound()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getRound());
      }
      if (hasBySelfy()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, getBySelfy());
      }
      if (hasLaizi()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, getLaizi());
      }
      if (hasUseDouble()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, getUseDouble());
      }
      if (hasTargetRound()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, getTargetRound());
      }
      if (hasGameType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(6, getGameType().getNumber());
      }
      if (hasLeizi()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, getLeizi());
      }
      if (hasHuangfan()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, getHuangfan());
      }
      if (hasDi()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, getDi());
      }
      if (hasFly()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, getFly());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.shanghaimajiang_server.protocol.Entity.NewGameConfigData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Entity.NewGameConfigData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Entity.NewGameConfigData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Entity.NewGameConfigData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Entity.NewGameConfigData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Entity.NewGameConfigData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Entity.NewGameConfigData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shanghaimajiang_server.protocol.Entity.NewGameConfigData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shanghaimajiang_server.protocol.Entity.NewGameConfigData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Entity.NewGameConfigData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.shanghaimajiang_server.protocol.Entity.NewGameConfigData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.shanghaimajiang_server.protocol.Entity.NewGameConfigData result;
      
      // Construct using com.randioo.shanghaimajiang_server.protocol.Entity.NewGameConfigData.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.shanghaimajiang_server.protocol.Entity.NewGameConfigData();
        return builder;
      }
      
      protected com.randioo.shanghaimajiang_server.protocol.Entity.NewGameConfigData internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.shanghaimajiang_server.protocol.Entity.NewGameConfigData();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.shanghaimajiang_server.protocol.Entity.NewGameConfigData.getDescriptor();
      }
      
      public com.randioo.shanghaimajiang_server.protocol.Entity.NewGameConfigData getDefaultInstanceForType() {
        return com.randioo.shanghaimajiang_server.protocol.Entity.NewGameConfigData.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.shanghaimajiang_server.protocol.Entity.NewGameConfigData build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.shanghaimajiang_server.protocol.Entity.NewGameConfigData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.shanghaimajiang_server.protocol.Entity.NewGameConfigData buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.shanghaimajiang_server.protocol.Entity.NewGameConfigData returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.shanghaimajiang_server.protocol.Entity.NewGameConfigData) {
          return mergeFrom((com.randioo.shanghaimajiang_server.protocol.Entity.NewGameConfigData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.shanghaimajiang_server.protocol.Entity.NewGameConfigData other) {
        if (other == com.randioo.shanghaimajiang_server.protocol.Entity.NewGameConfigData.getDefaultInstance()) return this;
        if (other.hasRound()) {
          setRound(other.getRound());
        }
        if (other.hasBySelfy()) {
          setBySelfy(other.getBySelfy());
        }
        if (other.hasLaizi()) {
          setLaizi(other.getLaizi());
        }
        if (other.hasUseDouble()) {
          setUseDouble(other.getUseDouble());
        }
        if (other.hasTargetRound()) {
          setTargetRound(other.getTargetRound());
        }
        if (other.hasGameType()) {
          setGameType(other.getGameType());
        }
        if (other.hasLeizi()) {
          setLeizi(other.getLeizi());
        }
        if (other.hasHuangfan()) {
          setHuangfan(other.getHuangfan());
        }
        if (other.hasDi()) {
          setDi(other.getDi());
        }
        if (other.hasFly()) {
          setFly(other.getFly());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setRound(input.readInt32());
              break;
            }
            case 16: {
              setBySelfy(input.readBool());
              break;
            }
            case 24: {
              setLaizi(input.readBool());
              break;
            }
            case 32: {
              setUseDouble(input.readBool());
              break;
            }
            case 40: {
              setTargetRound(input.readInt32());
              break;
            }
            case 48: {
              int rawValue = input.readEnum();
              com.randioo.shanghaimajiang_server.protocol.Entity.GameType value = com.randioo.shanghaimajiang_server.protocol.Entity.GameType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(6, rawValue);
              } else {
                setGameType(value);
              }
              break;
            }
            case 56: {
              setLeizi(input.readBool());
              break;
            }
            case 64: {
              setHuangfan(input.readBool());
              break;
            }
            case 72: {
              setDi(input.readInt32());
              break;
            }
            case 80: {
              setFly(input.readBool());
              break;
            }
          }
        }
      }
      
      
      // optional int32 round = 1;
      public boolean hasRound() {
        return result.hasRound();
      }
      public int getRound() {
        return result.getRound();
      }
      public Builder setRound(int value) {
        result.hasRound = true;
        result.round_ = value;
        return this;
      }
      public Builder clearRound() {
        result.hasRound = false;
        result.round_ = 0;
        return this;
      }
      
      // optional bool bySelfy = 2;
      public boolean hasBySelfy() {
        return result.hasBySelfy();
      }
      public boolean getBySelfy() {
        return result.getBySelfy();
      }
      public Builder setBySelfy(boolean value) {
        result.hasBySelfy = true;
        result.bySelfy_ = value;
        return this;
      }
      public Builder clearBySelfy() {
        result.hasBySelfy = false;
        result.bySelfy_ = false;
        return this;
      }
      
      // optional bool laizi = 3;
      public boolean hasLaizi() {
        return result.hasLaizi();
      }
      public boolean getLaizi() {
        return result.getLaizi();
      }
      public Builder setLaizi(boolean value) {
        result.hasLaizi = true;
        result.laizi_ = value;
        return this;
      }
      public Builder clearLaizi() {
        result.hasLaizi = false;
        result.laizi_ = false;
        return this;
      }
      
      // optional bool useDouble = 4;
      public boolean hasUseDouble() {
        return result.hasUseDouble();
      }
      public boolean getUseDouble() {
        return result.getUseDouble();
      }
      public Builder setUseDouble(boolean value) {
        result.hasUseDouble = true;
        result.useDouble_ = value;
        return this;
      }
      public Builder clearUseDouble() {
        result.hasUseDouble = false;
        result.useDouble_ = false;
        return this;
      }
      
      // optional int32 targetRound = 5;
      public boolean hasTargetRound() {
        return result.hasTargetRound();
      }
      public int getTargetRound() {
        return result.getTargetRound();
      }
      public Builder setTargetRound(int value) {
        result.hasTargetRound = true;
        result.targetRound_ = value;
        return this;
      }
      public Builder clearTargetRound() {
        result.hasTargetRound = false;
        result.targetRound_ = 0;
        return this;
      }
      
      // optional .com.randioo.shanghaimajiang_server.protocol.GameType gameType = 6;
      public boolean hasGameType() {
        return result.hasGameType();
      }
      public com.randioo.shanghaimajiang_server.protocol.Entity.GameType getGameType() {
        return result.getGameType();
      }
      public Builder setGameType(com.randioo.shanghaimajiang_server.protocol.Entity.GameType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasGameType = true;
        result.gameType_ = value;
        return this;
      }
      public Builder clearGameType() {
        result.hasGameType = false;
        result.gameType_ = com.randioo.shanghaimajiang_server.protocol.Entity.GameType.GAME_TYPE_YINSANZUI;
        return this;
      }
      
      // optional bool leizi = 7;
      public boolean hasLeizi() {
        return result.hasLeizi();
      }
      public boolean getLeizi() {
        return result.getLeizi();
      }
      public Builder setLeizi(boolean value) {
        result.hasLeizi = true;
        result.leizi_ = value;
        return this;
      }
      public Builder clearLeizi() {
        result.hasLeizi = false;
        result.leizi_ = false;
        return this;
      }
      
      // optional bool huangfan = 8;
      public boolean hasHuangfan() {
        return result.hasHuangfan();
      }
      public boolean getHuangfan() {
        return result.getHuangfan();
      }
      public Builder setHuangfan(boolean value) {
        result.hasHuangfan = true;
        result.huangfan_ = value;
        return this;
      }
      public Builder clearHuangfan() {
        result.hasHuangfan = false;
        result.huangfan_ = false;
        return this;
      }
      
      // optional int32 di = 9;
      public boolean hasDi() {
        return result.hasDi();
      }
      public int getDi() {
        return result.getDi();
      }
      public Builder setDi(int value) {
        result.hasDi = true;
        result.di_ = value;
        return this;
      }
      public Builder clearDi() {
        result.hasDi = false;
        result.di_ = 0;
        return this;
      }
      
      // optional bool fly = 10;
      public boolean hasFly() {
        return result.hasFly();
      }
      public boolean getFly() {
        return result.getFly();
      }
      public Builder setFly(boolean value) {
        result.hasFly = true;
        result.fly_ = value;
        return this;
      }
      public Builder clearFly() {
        result.hasFly = false;
        result.fly_ = false;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.shanghaimajiang_server.protocol.NewGameConfigData)
    }
    
    static {
      defaultInstance = new NewGameConfigData(true);
      com.randioo.shanghaimajiang_server.protocol.Entity.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.shanghaimajiang_server.protocol.NewGameConfigData)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_shanghaimajiang_server_protocol_RoleData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_shanghaimajiang_server_protocol_RoleData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_shanghaimajiang_server_protocol_NewGameConfigData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_shanghaimajiang_server_protocol_NewGameConfigData_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Entity.proto\022+com.randioo.shanghaimaji" +
      "ang_server.protocol\"(\n\010RoleData\022\016\n\006roleI" +
      "d\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\"\355\001\n\021NewGameConfigD" +
      "ata\022\r\n\005round\030\001 \001(\005\022\017\n\007bySelfy\030\002 \001(\010\022\r\n\005l" +
      "aizi\030\003 \001(\010\022\021\n\tuseDouble\030\004 \001(\010\022\023\n\013targetR" +
      "ound\030\005 \001(\005\022G\n\010gameType\030\006 \001(\01625.com.randi" +
      "oo.shanghaimajiang_server.protocol.GameT" +
      "ype\022\r\n\005leizi\030\007 \001(\010\022\020\n\010huangfan\030\010 \001(\010\022\n\n\002" +
      "di\030\t \001(\005\022\013\n\003fly\030\n \001(\010*k\n\010GameType\022\027\n\023GAM" +
      "E_TYPE_YINSANZUI\020\000\022\025\n\021GAME_TYPE_KOUDIAN\020",
      "\001\022\024\n\020GAME_TYPE_QIAOMA\020\002\022\031\n\025GAME_TYPE_QIN" +
      "GHUNPENG\020\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_shanghaimajiang_server_protocol_RoleData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_shanghaimajiang_server_protocol_RoleData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_shanghaimajiang_server_protocol_RoleData_descriptor,
              new java.lang.String[] { "RoleId", "Name", },
              com.randioo.shanghaimajiang_server.protocol.Entity.RoleData.class,
              com.randioo.shanghaimajiang_server.protocol.Entity.RoleData.Builder.class);
          internal_static_com_randioo_shanghaimajiang_server_protocol_NewGameConfigData_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_randioo_shanghaimajiang_server_protocol_NewGameConfigData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_shanghaimajiang_server_protocol_NewGameConfigData_descriptor,
              new java.lang.String[] { "Round", "BySelfy", "Laizi", "UseDouble", "TargetRound", "GameType", "Leizi", "Huangfan", "Di", "Fly", },
              com.randioo.shanghaimajiang_server.protocol.Entity.NewGameConfigData.class,
              com.randioo.shanghaimajiang_server.protocol.Entity.NewGameConfigData.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
