// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Error.proto

package com.randioo.shanghaimajiang_server.protocol;

public final class Error {
  private Error() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum ErrorCode
      implements com.google.protobuf.ProtocolMessageEnum {
    OK(0, 1),
    NO_STRING(1, 2),
    NO_ROLE_ACCOUNT(2, 3),
    EXIST_ROLE(3, 4),
    CREATE_FAILED(4, 5),
    REJECT_LOGIN(5, 6),
    ACCOUNT_ILLEGEL(6, 7),
    IN_LOGIN(7, 8),
    NAME_SENSITIVE(8, 9),
    NO_ROLE_DATA(9, 10),
    NAME_REPEATED(10, 11),
    NAME_TOO_LONG(11, 12),
    NAME_SPECIAL_CHAR(12, 13),
    ;
    
    
    public final int getNumber() { return value; }
    
    public static ErrorCode valueOf(int value) {
      switch (value) {
        case 1: return OK;
        case 2: return NO_STRING;
        case 3: return NO_ROLE_ACCOUNT;
        case 4: return EXIST_ROLE;
        case 5: return CREATE_FAILED;
        case 6: return REJECT_LOGIN;
        case 7: return ACCOUNT_ILLEGEL;
        case 8: return IN_LOGIN;
        case 9: return NAME_SENSITIVE;
        case 10: return NO_ROLE_DATA;
        case 11: return NAME_REPEATED;
        case 12: return NAME_TOO_LONG;
        case 13: return NAME_SPECIAL_CHAR;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrorCode>() {
            public ErrorCode findValueByNumber(int number) {
              return ErrorCode.valueOf(number)
    ;        }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.randioo.shanghaimajiang_server.protocol.Error.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final ErrorCode[] VALUES = {
      OK, NO_STRING, NO_ROLE_ACCOUNT, EXIST_ROLE, CREATE_FAILED, REJECT_LOGIN, ACCOUNT_ILLEGEL, IN_LOGIN, NAME_SENSITIVE, NO_ROLE_DATA, NAME_REPEATED, NAME_TOO_LONG, NAME_SPECIAL_CHAR, 
    };
    public static ErrorCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    private final int index;
    private final int value;
    private ErrorCode(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    static {
      com.randioo.shanghaimajiang_server.protocol.Error.getDescriptor();
    }
    
    // @@protoc_insertion_point(enum_scope:com.randioo.shanghaimajiang_server.protocol.ErrorCode)
  }
  
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Error.proto\022+com.randioo.shanghaimajia" +
      "ng_server.protocol*\362\001\n\tErrorCode\022\006\n\002OK\020\001" +
      "\022\r\n\tNO_STRING\020\002\022\023\n\017NO_ROLE_ACCOUNT\020\003\022\016\n\n" +
      "EXIST_ROLE\020\004\022\021\n\rCREATE_FAILED\020\005\022\020\n\014REJEC" +
      "T_LOGIN\020\006\022\023\n\017ACCOUNT_ILLEGEL\020\007\022\014\n\010IN_LOG" +
      "IN\020\010\022\022\n\016NAME_SENSITIVE\020\t\022\020\n\014NO_ROLE_DATA" +
      "\020\n\022\021\n\rNAME_REPEATED\020\013\022\021\n\rNAME_TOO_LONG\020\014" +
      "\022\025\n\021NAME_SPECIAL_CHAR\020\r"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
