// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Fight.proto

package com.randioo.shanghaimajiang_server.protocol;

public final class Fight {
  private Fight() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class SCFightWait extends
      com.google.protobuf.GeneratedMessage {
    // Use SCFightWait.newBuilder() to construct.
    private SCFightWait() {
      initFields();
    }
    private SCFightWait(boolean noInit) {}
    
    private static final SCFightWait defaultInstance;
    public static SCFightWait getDefaultInstance() {
      return defaultInstance;
    }
    
    public SCFightWait getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.shanghaimajiang_server.protocol.Fight.internal_static_com_randioo_shanghaimajiang_server_protocol_SCFightWait_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.shanghaimajiang_server.protocol.Fight.internal_static_com_randioo_shanghaimajiang_server_protocol_SCFightWait_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait result;
      
      // Construct using com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait();
        return builder;
      }
      
      protected com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait.getDescriptor();
      }
      
      public com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait getDefaultInstanceForType() {
        return com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait) {
          return mergeFrom((com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait other) {
        if (other == com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.randioo.shanghaimajiang_server.protocol.SCFightWait)
    }
    
    static {
      defaultInstance = new SCFightWait(true);
      com.randioo.shanghaimajiang_server.protocol.Fight.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.shanghaimajiang_server.protocol.SCFightWait)
  }
  
  public static final class FightCmdRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use FightCmdRequest.newBuilder() to construct.
    private FightCmdRequest() {
      initFields();
    }
    private FightCmdRequest(boolean noInit) {}
    
    private static final FightCmdRequest defaultInstance;
    public static FightCmdRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public FightCmdRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.shanghaimajiang_server.protocol.Fight.internal_static_com_randioo_shanghaimajiang_server_protocol_FightCmdRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.shanghaimajiang_server.protocol.Fight.internal_static_com_randioo_shanghaimajiang_server_protocol_FightCmdRequest_fieldAccessorTable;
    }
    
    // optional .com.randioo.shanghaimajiang_server.protocol.GameActionData gameActionData = 1;
    public static final int GAMEACTIONDATA_FIELD_NUMBER = 1;
    private boolean hasGameActionData;
    private com.randioo.shanghaimajiang_server.protocol.Entity.GameActionData gameActionData_;
    public boolean hasGameActionData() { return hasGameActionData; }
    public com.randioo.shanghaimajiang_server.protocol.Entity.GameActionData getGameActionData() { return gameActionData_; }
    
    private void initFields() {
      gameActionData_ = com.randioo.shanghaimajiang_server.protocol.Entity.GameActionData.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasGameActionData()) {
        output.writeMessage(1, getGameActionData());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasGameActionData()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getGameActionData());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest result;
      
      // Construct using com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest();
        return builder;
      }
      
      protected com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest.getDescriptor();
      }
      
      public com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest getDefaultInstanceForType() {
        return com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest) {
          return mergeFrom((com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest other) {
        if (other == com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest.getDefaultInstance()) return this;
        if (other.hasGameActionData()) {
          mergeGameActionData(other.getGameActionData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.randioo.shanghaimajiang_server.protocol.Entity.GameActionData.Builder subBuilder = com.randioo.shanghaimajiang_server.protocol.Entity.GameActionData.newBuilder();
              if (hasGameActionData()) {
                subBuilder.mergeFrom(getGameActionData());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGameActionData(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .com.randioo.shanghaimajiang_server.protocol.GameActionData gameActionData = 1;
      public boolean hasGameActionData() {
        return result.hasGameActionData();
      }
      public com.randioo.shanghaimajiang_server.protocol.Entity.GameActionData getGameActionData() {
        return result.getGameActionData();
      }
      public Builder setGameActionData(com.randioo.shanghaimajiang_server.protocol.Entity.GameActionData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasGameActionData = true;
        result.gameActionData_ = value;
        return this;
      }
      public Builder setGameActionData(com.randioo.shanghaimajiang_server.protocol.Entity.GameActionData.Builder builderForValue) {
        result.hasGameActionData = true;
        result.gameActionData_ = builderForValue.build();
        return this;
      }
      public Builder mergeGameActionData(com.randioo.shanghaimajiang_server.protocol.Entity.GameActionData value) {
        if (result.hasGameActionData() &&
            result.gameActionData_ != com.randioo.shanghaimajiang_server.protocol.Entity.GameActionData.getDefaultInstance()) {
          result.gameActionData_ =
            com.randioo.shanghaimajiang_server.protocol.Entity.GameActionData.newBuilder(result.gameActionData_).mergeFrom(value).buildPartial();
        } else {
          result.gameActionData_ = value;
        }
        result.hasGameActionData = true;
        return this;
      }
      public Builder clearGameActionData() {
        result.hasGameActionData = false;
        result.gameActionData_ = com.randioo.shanghaimajiang_server.protocol.Entity.GameActionData.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.shanghaimajiang_server.protocol.FightCmdRequest)
    }
    
    static {
      defaultInstance = new FightCmdRequest(true);
      com.randioo.shanghaimajiang_server.protocol.Fight.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.shanghaimajiang_server.protocol.FightCmdRequest)
  }
  
  public static final class FightCmdResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use FightCmdResponse.newBuilder() to construct.
    private FightCmdResponse() {
      initFields();
    }
    private FightCmdResponse(boolean noInit) {}
    
    private static final FightCmdResponse defaultInstance;
    public static FightCmdResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public FightCmdResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.shanghaimajiang_server.protocol.Fight.internal_static_com_randioo_shanghaimajiang_server_protocol_FightCmdResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.shanghaimajiang_server.protocol.Fight.internal_static_com_randioo_shanghaimajiang_server_protocol_FightCmdResponse_fieldAccessorTable;
    }
    
    // optional int32 errorCode = 1 [default = 1];
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private boolean hasErrorCode;
    private int errorCode_ = 1;
    public boolean hasErrorCode() { return hasErrorCode; }
    public int getErrorCode() { return errorCode_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasErrorCode()) {
        output.writeInt32(1, getErrorCode());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasErrorCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getErrorCode());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse result;
      
      // Construct using com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse();
        return builder;
      }
      
      protected com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse.getDescriptor();
      }
      
      public com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse getDefaultInstanceForType() {
        return com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse) {
          return mergeFrom((com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse other) {
        if (other == com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setErrorCode(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 errorCode = 1 [default = 1];
      public boolean hasErrorCode() {
        return result.hasErrorCode();
      }
      public int getErrorCode() {
        return result.getErrorCode();
      }
      public Builder setErrorCode(int value) {
        result.hasErrorCode = true;
        result.errorCode_ = value;
        return this;
      }
      public Builder clearErrorCode() {
        result.hasErrorCode = false;
        result.errorCode_ = 1;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.shanghaimajiang_server.protocol.FightCmdResponse)
    }
    
    static {
      defaultInstance = new FightCmdResponse(true);
      com.randioo.shanghaimajiang_server.protocol.Fight.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.shanghaimajiang_server.protocol.FightCmdResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_shanghaimajiang_server_protocol_SCFightWait_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_shanghaimajiang_server_protocol_SCFightWait_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_shanghaimajiang_server_protocol_FightCmdRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_shanghaimajiang_server_protocol_FightCmdRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_shanghaimajiang_server_protocol_FightCmdResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_shanghaimajiang_server_protocol_FightCmdResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Fight.proto\022+com.randioo.shanghaimajia" +
      "ng_server.protocol\032\014Entity.proto\"\r\n\013SCFi" +
      "ghtWait\"f\n\017FightCmdRequest\022S\n\016gameAction" +
      "Data\030\001 \001(\0132;.com.randioo.shanghaimajiang" +
      "_server.protocol.GameActionData\"(\n\020Fight" +
      "CmdResponse\022\024\n\terrorCode\030\001 \001(\005:\0011"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_shanghaimajiang_server_protocol_SCFightWait_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_shanghaimajiang_server_protocol_SCFightWait_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_shanghaimajiang_server_protocol_SCFightWait_descriptor,
              new java.lang.String[] { },
              com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait.class,
              com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait.Builder.class);
          internal_static_com_randioo_shanghaimajiang_server_protocol_FightCmdRequest_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_randioo_shanghaimajiang_server_protocol_FightCmdRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_shanghaimajiang_server_protocol_FightCmdRequest_descriptor,
              new java.lang.String[] { "GameActionData", },
              com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest.class,
              com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdRequest.Builder.class);
          internal_static_com_randioo_shanghaimajiang_server_protocol_FightCmdResponse_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_randioo_shanghaimajiang_server_protocol_FightCmdResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_shanghaimajiang_server_protocol_FightCmdResponse_descriptor,
              new java.lang.String[] { "ErrorCode", },
              com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse.class,
              com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.shanghaimajiang_server.protocol.Entity.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
