// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerMessage.proto

package com.randioo.shanghaimajiang_server.protocol;

public final class ServerMessage {
  private ServerMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class SC extends
      com.google.protobuf.GeneratedMessage {
    // Use SC.newBuilder() to construct.
    private SC() {
      initFields();
    }
    private SC(boolean noInit) {}
    
    private static final SC defaultInstance;
    public static SC getDefaultInstance() {
      return defaultInstance;
    }
    
    public SC getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.shanghaimajiang_server.protocol.ServerMessage.internal_static_com_randioo_shanghaimajiang_server_protocol_SC_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.shanghaimajiang_server.protocol.ServerMessage.internal_static_com_randioo_shanghaimajiang_server_protocol_SC_fieldAccessorTable;
    }
    
    // optional .com.randioo.shanghaimajiang_server.protocol.LoginCheckAccountResponse LoginCheckAccountResponse = 1;
    public static final int LOGINCHECKACCOUNTRESPONSE_FIELD_NUMBER = 1;
    private boolean hasLoginCheckAccountResponse;
    private com.randioo.shanghaimajiang_server.protocol.Login.LoginCheckAccountResponse loginCheckAccountResponse_;
    public boolean hasLoginCheckAccountResponse() { return hasLoginCheckAccountResponse; }
    public com.randioo.shanghaimajiang_server.protocol.Login.LoginCheckAccountResponse getLoginCheckAccountResponse() { return loginCheckAccountResponse_; }
    
    // optional .com.randioo.shanghaimajiang_server.protocol.LoginCreateRoleResponse LoginCreateRoleResponse = 2;
    public static final int LOGINCREATEROLERESPONSE_FIELD_NUMBER = 2;
    private boolean hasLoginCreateRoleResponse;
    private com.randioo.shanghaimajiang_server.protocol.Login.LoginCreateRoleResponse loginCreateRoleResponse_;
    public boolean hasLoginCreateRoleResponse() { return hasLoginCreateRoleResponse; }
    public com.randioo.shanghaimajiang_server.protocol.Login.LoginCreateRoleResponse getLoginCreateRoleResponse() { return loginCreateRoleResponse_; }
    
    // optional .com.randioo.shanghaimajiang_server.protocol.LoginGetRoleDataResponse LoginGetRoleDataResponse = 3;
    public static final int LOGINGETROLEDATARESPONSE_FIELD_NUMBER = 3;
    private boolean hasLoginGetRoleDataResponse;
    private com.randioo.shanghaimajiang_server.protocol.Login.LoginGetRoleDataResponse loginGetRoleDataResponse_;
    public boolean hasLoginGetRoleDataResponse() { return hasLoginGetRoleDataResponse; }
    public com.randioo.shanghaimajiang_server.protocol.Login.LoginGetRoleDataResponse getLoginGetRoleDataResponse() { return loginGetRoleDataResponse_; }
    
    // optional .com.randioo.shanghaimajiang_server.protocol.RoleRenameResponse RoleRenameResponse = 4;
    public static final int ROLERENAMERESPONSE_FIELD_NUMBER = 4;
    private boolean hasRoleRenameResponse;
    private com.randioo.shanghaimajiang_server.protocol.Role.RoleRenameResponse roleRenameResponse_;
    public boolean hasRoleRenameResponse() { return hasRoleRenameResponse; }
    public com.randioo.shanghaimajiang_server.protocol.Role.RoleRenameResponse getRoleRenameResponse() { return roleRenameResponse_; }
    
    // optional .com.randioo.shanghaimajiang_server.protocol.MatchNewGameResponse MatchNewGameResponse = 5;
    public static final int MATCHNEWGAMERESPONSE_FIELD_NUMBER = 5;
    private boolean hasMatchNewGameResponse;
    private com.randioo.shanghaimajiang_server.protocol.Match.MatchNewGameResponse matchNewGameResponse_;
    public boolean hasMatchNewGameResponse() { return hasMatchNewGameResponse; }
    public com.randioo.shanghaimajiang_server.protocol.Match.MatchNewGameResponse getMatchNewGameResponse() { return matchNewGameResponse_; }
    
    // optional .com.randioo.shanghaimajiang_server.protocol.MatchJoinGameResponse MatchJoinGameResponse = 6;
    public static final int MATCHJOINGAMERESPONSE_FIELD_NUMBER = 6;
    private boolean hasMatchJoinGameResponse;
    private com.randioo.shanghaimajiang_server.protocol.Match.MatchJoinGameResponse matchJoinGameResponse_;
    public boolean hasMatchJoinGameResponse() { return hasMatchJoinGameResponse; }
    public com.randioo.shanghaimajiang_server.protocol.Match.MatchJoinGameResponse getMatchJoinGameResponse() { return matchJoinGameResponse_; }
    
    // optional .com.randioo.shanghaimajiang_server.protocol.FightCmdResponse FightCmdResponse = 7;
    public static final int FIGHTCMDRESPONSE_FIELD_NUMBER = 7;
    private boolean hasFightCmdResponse;
    private com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse fightCmdResponse_;
    public boolean hasFightCmdResponse() { return hasFightCmdResponse; }
    public com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse getFightCmdResponse() { return fightCmdResponse_; }
    
    // optional .com.randioo.shanghaimajiang_server.protocol.SCFightWait SCFightWait = 8;
    public static final int SCFIGHTWAIT_FIELD_NUMBER = 8;
    private boolean hasSCFightWait;
    private com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait sCFightWait_;
    public boolean hasSCFightWait() { return hasSCFightWait; }
    public com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait getSCFightWait() { return sCFightWait_; }
    
    private void initFields() {
      loginCheckAccountResponse_ = com.randioo.shanghaimajiang_server.protocol.Login.LoginCheckAccountResponse.getDefaultInstance();
      loginCreateRoleResponse_ = com.randioo.shanghaimajiang_server.protocol.Login.LoginCreateRoleResponse.getDefaultInstance();
      loginGetRoleDataResponse_ = com.randioo.shanghaimajiang_server.protocol.Login.LoginGetRoleDataResponse.getDefaultInstance();
      roleRenameResponse_ = com.randioo.shanghaimajiang_server.protocol.Role.RoleRenameResponse.getDefaultInstance();
      matchNewGameResponse_ = com.randioo.shanghaimajiang_server.protocol.Match.MatchNewGameResponse.getDefaultInstance();
      matchJoinGameResponse_ = com.randioo.shanghaimajiang_server.protocol.Match.MatchJoinGameResponse.getDefaultInstance();
      fightCmdResponse_ = com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse.getDefaultInstance();
      sCFightWait_ = com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasLoginCheckAccountResponse()) {
        output.writeMessage(1, getLoginCheckAccountResponse());
      }
      if (hasLoginCreateRoleResponse()) {
        output.writeMessage(2, getLoginCreateRoleResponse());
      }
      if (hasLoginGetRoleDataResponse()) {
        output.writeMessage(3, getLoginGetRoleDataResponse());
      }
      if (hasRoleRenameResponse()) {
        output.writeMessage(4, getRoleRenameResponse());
      }
      if (hasMatchNewGameResponse()) {
        output.writeMessage(5, getMatchNewGameResponse());
      }
      if (hasMatchJoinGameResponse()) {
        output.writeMessage(6, getMatchJoinGameResponse());
      }
      if (hasFightCmdResponse()) {
        output.writeMessage(7, getFightCmdResponse());
      }
      if (hasSCFightWait()) {
        output.writeMessage(8, getSCFightWait());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasLoginCheckAccountResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getLoginCheckAccountResponse());
      }
      if (hasLoginCreateRoleResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getLoginCreateRoleResponse());
      }
      if (hasLoginGetRoleDataResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getLoginGetRoleDataResponse());
      }
      if (hasRoleRenameResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getRoleRenameResponse());
      }
      if (hasMatchNewGameResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getMatchNewGameResponse());
      }
      if (hasMatchJoinGameResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getMatchJoinGameResponse());
      }
      if (hasFightCmdResponse()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getFightCmdResponse());
      }
      if (hasSCFightWait()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getSCFightWait());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.shanghaimajiang_server.protocol.ServerMessage.SC parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.ServerMessage.SC parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.ServerMessage.SC parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.ServerMessage.SC parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.ServerMessage.SC parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.ServerMessage.SC parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.ServerMessage.SC parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shanghaimajiang_server.protocol.ServerMessage.SC parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.shanghaimajiang_server.protocol.ServerMessage.SC parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.shanghaimajiang_server.protocol.ServerMessage.SC parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.shanghaimajiang_server.protocol.ServerMessage.SC prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.shanghaimajiang_server.protocol.ServerMessage.SC result;
      
      // Construct using com.randioo.shanghaimajiang_server.protocol.ServerMessage.SC.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.shanghaimajiang_server.protocol.ServerMessage.SC();
        return builder;
      }
      
      protected com.randioo.shanghaimajiang_server.protocol.ServerMessage.SC internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.shanghaimajiang_server.protocol.ServerMessage.SC();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.shanghaimajiang_server.protocol.ServerMessage.SC.getDescriptor();
      }
      
      public com.randioo.shanghaimajiang_server.protocol.ServerMessage.SC getDefaultInstanceForType() {
        return com.randioo.shanghaimajiang_server.protocol.ServerMessage.SC.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.shanghaimajiang_server.protocol.ServerMessage.SC build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.shanghaimajiang_server.protocol.ServerMessage.SC buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.shanghaimajiang_server.protocol.ServerMessage.SC buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.shanghaimajiang_server.protocol.ServerMessage.SC returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.shanghaimajiang_server.protocol.ServerMessage.SC) {
          return mergeFrom((com.randioo.shanghaimajiang_server.protocol.ServerMessage.SC)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.shanghaimajiang_server.protocol.ServerMessage.SC other) {
        if (other == com.randioo.shanghaimajiang_server.protocol.ServerMessage.SC.getDefaultInstance()) return this;
        if (other.hasLoginCheckAccountResponse()) {
          mergeLoginCheckAccountResponse(other.getLoginCheckAccountResponse());
        }
        if (other.hasLoginCreateRoleResponse()) {
          mergeLoginCreateRoleResponse(other.getLoginCreateRoleResponse());
        }
        if (other.hasLoginGetRoleDataResponse()) {
          mergeLoginGetRoleDataResponse(other.getLoginGetRoleDataResponse());
        }
        if (other.hasRoleRenameResponse()) {
          mergeRoleRenameResponse(other.getRoleRenameResponse());
        }
        if (other.hasMatchNewGameResponse()) {
          mergeMatchNewGameResponse(other.getMatchNewGameResponse());
        }
        if (other.hasMatchJoinGameResponse()) {
          mergeMatchJoinGameResponse(other.getMatchJoinGameResponse());
        }
        if (other.hasFightCmdResponse()) {
          mergeFightCmdResponse(other.getFightCmdResponse());
        }
        if (other.hasSCFightWait()) {
          mergeSCFightWait(other.getSCFightWait());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.randioo.shanghaimajiang_server.protocol.Login.LoginCheckAccountResponse.Builder subBuilder = com.randioo.shanghaimajiang_server.protocol.Login.LoginCheckAccountResponse.newBuilder();
              if (hasLoginCheckAccountResponse()) {
                subBuilder.mergeFrom(getLoginCheckAccountResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginCheckAccountResponse(subBuilder.buildPartial());
              break;
            }
            case 18: {
              com.randioo.shanghaimajiang_server.protocol.Login.LoginCreateRoleResponse.Builder subBuilder = com.randioo.shanghaimajiang_server.protocol.Login.LoginCreateRoleResponse.newBuilder();
              if (hasLoginCreateRoleResponse()) {
                subBuilder.mergeFrom(getLoginCreateRoleResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginCreateRoleResponse(subBuilder.buildPartial());
              break;
            }
            case 26: {
              com.randioo.shanghaimajiang_server.protocol.Login.LoginGetRoleDataResponse.Builder subBuilder = com.randioo.shanghaimajiang_server.protocol.Login.LoginGetRoleDataResponse.newBuilder();
              if (hasLoginGetRoleDataResponse()) {
                subBuilder.mergeFrom(getLoginGetRoleDataResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginGetRoleDataResponse(subBuilder.buildPartial());
              break;
            }
            case 34: {
              com.randioo.shanghaimajiang_server.protocol.Role.RoleRenameResponse.Builder subBuilder = com.randioo.shanghaimajiang_server.protocol.Role.RoleRenameResponse.newBuilder();
              if (hasRoleRenameResponse()) {
                subBuilder.mergeFrom(getRoleRenameResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setRoleRenameResponse(subBuilder.buildPartial());
              break;
            }
            case 42: {
              com.randioo.shanghaimajiang_server.protocol.Match.MatchNewGameResponse.Builder subBuilder = com.randioo.shanghaimajiang_server.protocol.Match.MatchNewGameResponse.newBuilder();
              if (hasMatchNewGameResponse()) {
                subBuilder.mergeFrom(getMatchNewGameResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMatchNewGameResponse(subBuilder.buildPartial());
              break;
            }
            case 50: {
              com.randioo.shanghaimajiang_server.protocol.Match.MatchJoinGameResponse.Builder subBuilder = com.randioo.shanghaimajiang_server.protocol.Match.MatchJoinGameResponse.newBuilder();
              if (hasMatchJoinGameResponse()) {
                subBuilder.mergeFrom(getMatchJoinGameResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMatchJoinGameResponse(subBuilder.buildPartial());
              break;
            }
            case 58: {
              com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse.Builder subBuilder = com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse.newBuilder();
              if (hasFightCmdResponse()) {
                subBuilder.mergeFrom(getFightCmdResponse());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setFightCmdResponse(subBuilder.buildPartial());
              break;
            }
            case 66: {
              com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait.Builder subBuilder = com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait.newBuilder();
              if (hasSCFightWait()) {
                subBuilder.mergeFrom(getSCFightWait());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSCFightWait(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .com.randioo.shanghaimajiang_server.protocol.LoginCheckAccountResponse LoginCheckAccountResponse = 1;
      public boolean hasLoginCheckAccountResponse() {
        return result.hasLoginCheckAccountResponse();
      }
      public com.randioo.shanghaimajiang_server.protocol.Login.LoginCheckAccountResponse getLoginCheckAccountResponse() {
        return result.getLoginCheckAccountResponse();
      }
      public Builder setLoginCheckAccountResponse(com.randioo.shanghaimajiang_server.protocol.Login.LoginCheckAccountResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginCheckAccountResponse = true;
        result.loginCheckAccountResponse_ = value;
        return this;
      }
      public Builder setLoginCheckAccountResponse(com.randioo.shanghaimajiang_server.protocol.Login.LoginCheckAccountResponse.Builder builderForValue) {
        result.hasLoginCheckAccountResponse = true;
        result.loginCheckAccountResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginCheckAccountResponse(com.randioo.shanghaimajiang_server.protocol.Login.LoginCheckAccountResponse value) {
        if (result.hasLoginCheckAccountResponse() &&
            result.loginCheckAccountResponse_ != com.randioo.shanghaimajiang_server.protocol.Login.LoginCheckAccountResponse.getDefaultInstance()) {
          result.loginCheckAccountResponse_ =
            com.randioo.shanghaimajiang_server.protocol.Login.LoginCheckAccountResponse.newBuilder(result.loginCheckAccountResponse_).mergeFrom(value).buildPartial();
        } else {
          result.loginCheckAccountResponse_ = value;
        }
        result.hasLoginCheckAccountResponse = true;
        return this;
      }
      public Builder clearLoginCheckAccountResponse() {
        result.hasLoginCheckAccountResponse = false;
        result.loginCheckAccountResponse_ = com.randioo.shanghaimajiang_server.protocol.Login.LoginCheckAccountResponse.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.shanghaimajiang_server.protocol.LoginCreateRoleResponse LoginCreateRoleResponse = 2;
      public boolean hasLoginCreateRoleResponse() {
        return result.hasLoginCreateRoleResponse();
      }
      public com.randioo.shanghaimajiang_server.protocol.Login.LoginCreateRoleResponse getLoginCreateRoleResponse() {
        return result.getLoginCreateRoleResponse();
      }
      public Builder setLoginCreateRoleResponse(com.randioo.shanghaimajiang_server.protocol.Login.LoginCreateRoleResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginCreateRoleResponse = true;
        result.loginCreateRoleResponse_ = value;
        return this;
      }
      public Builder setLoginCreateRoleResponse(com.randioo.shanghaimajiang_server.protocol.Login.LoginCreateRoleResponse.Builder builderForValue) {
        result.hasLoginCreateRoleResponse = true;
        result.loginCreateRoleResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginCreateRoleResponse(com.randioo.shanghaimajiang_server.protocol.Login.LoginCreateRoleResponse value) {
        if (result.hasLoginCreateRoleResponse() &&
            result.loginCreateRoleResponse_ != com.randioo.shanghaimajiang_server.protocol.Login.LoginCreateRoleResponse.getDefaultInstance()) {
          result.loginCreateRoleResponse_ =
            com.randioo.shanghaimajiang_server.protocol.Login.LoginCreateRoleResponse.newBuilder(result.loginCreateRoleResponse_).mergeFrom(value).buildPartial();
        } else {
          result.loginCreateRoleResponse_ = value;
        }
        result.hasLoginCreateRoleResponse = true;
        return this;
      }
      public Builder clearLoginCreateRoleResponse() {
        result.hasLoginCreateRoleResponse = false;
        result.loginCreateRoleResponse_ = com.randioo.shanghaimajiang_server.protocol.Login.LoginCreateRoleResponse.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.shanghaimajiang_server.protocol.LoginGetRoleDataResponse LoginGetRoleDataResponse = 3;
      public boolean hasLoginGetRoleDataResponse() {
        return result.hasLoginGetRoleDataResponse();
      }
      public com.randioo.shanghaimajiang_server.protocol.Login.LoginGetRoleDataResponse getLoginGetRoleDataResponse() {
        return result.getLoginGetRoleDataResponse();
      }
      public Builder setLoginGetRoleDataResponse(com.randioo.shanghaimajiang_server.protocol.Login.LoginGetRoleDataResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginGetRoleDataResponse = true;
        result.loginGetRoleDataResponse_ = value;
        return this;
      }
      public Builder setLoginGetRoleDataResponse(com.randioo.shanghaimajiang_server.protocol.Login.LoginGetRoleDataResponse.Builder builderForValue) {
        result.hasLoginGetRoleDataResponse = true;
        result.loginGetRoleDataResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginGetRoleDataResponse(com.randioo.shanghaimajiang_server.protocol.Login.LoginGetRoleDataResponse value) {
        if (result.hasLoginGetRoleDataResponse() &&
            result.loginGetRoleDataResponse_ != com.randioo.shanghaimajiang_server.protocol.Login.LoginGetRoleDataResponse.getDefaultInstance()) {
          result.loginGetRoleDataResponse_ =
            com.randioo.shanghaimajiang_server.protocol.Login.LoginGetRoleDataResponse.newBuilder(result.loginGetRoleDataResponse_).mergeFrom(value).buildPartial();
        } else {
          result.loginGetRoleDataResponse_ = value;
        }
        result.hasLoginGetRoleDataResponse = true;
        return this;
      }
      public Builder clearLoginGetRoleDataResponse() {
        result.hasLoginGetRoleDataResponse = false;
        result.loginGetRoleDataResponse_ = com.randioo.shanghaimajiang_server.protocol.Login.LoginGetRoleDataResponse.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.shanghaimajiang_server.protocol.RoleRenameResponse RoleRenameResponse = 4;
      public boolean hasRoleRenameResponse() {
        return result.hasRoleRenameResponse();
      }
      public com.randioo.shanghaimajiang_server.protocol.Role.RoleRenameResponse getRoleRenameResponse() {
        return result.getRoleRenameResponse();
      }
      public Builder setRoleRenameResponse(com.randioo.shanghaimajiang_server.protocol.Role.RoleRenameResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasRoleRenameResponse = true;
        result.roleRenameResponse_ = value;
        return this;
      }
      public Builder setRoleRenameResponse(com.randioo.shanghaimajiang_server.protocol.Role.RoleRenameResponse.Builder builderForValue) {
        result.hasRoleRenameResponse = true;
        result.roleRenameResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeRoleRenameResponse(com.randioo.shanghaimajiang_server.protocol.Role.RoleRenameResponse value) {
        if (result.hasRoleRenameResponse() &&
            result.roleRenameResponse_ != com.randioo.shanghaimajiang_server.protocol.Role.RoleRenameResponse.getDefaultInstance()) {
          result.roleRenameResponse_ =
            com.randioo.shanghaimajiang_server.protocol.Role.RoleRenameResponse.newBuilder(result.roleRenameResponse_).mergeFrom(value).buildPartial();
        } else {
          result.roleRenameResponse_ = value;
        }
        result.hasRoleRenameResponse = true;
        return this;
      }
      public Builder clearRoleRenameResponse() {
        result.hasRoleRenameResponse = false;
        result.roleRenameResponse_ = com.randioo.shanghaimajiang_server.protocol.Role.RoleRenameResponse.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.shanghaimajiang_server.protocol.MatchNewGameResponse MatchNewGameResponse = 5;
      public boolean hasMatchNewGameResponse() {
        return result.hasMatchNewGameResponse();
      }
      public com.randioo.shanghaimajiang_server.protocol.Match.MatchNewGameResponse getMatchNewGameResponse() {
        return result.getMatchNewGameResponse();
      }
      public Builder setMatchNewGameResponse(com.randioo.shanghaimajiang_server.protocol.Match.MatchNewGameResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasMatchNewGameResponse = true;
        result.matchNewGameResponse_ = value;
        return this;
      }
      public Builder setMatchNewGameResponse(com.randioo.shanghaimajiang_server.protocol.Match.MatchNewGameResponse.Builder builderForValue) {
        result.hasMatchNewGameResponse = true;
        result.matchNewGameResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeMatchNewGameResponse(com.randioo.shanghaimajiang_server.protocol.Match.MatchNewGameResponse value) {
        if (result.hasMatchNewGameResponse() &&
            result.matchNewGameResponse_ != com.randioo.shanghaimajiang_server.protocol.Match.MatchNewGameResponse.getDefaultInstance()) {
          result.matchNewGameResponse_ =
            com.randioo.shanghaimajiang_server.protocol.Match.MatchNewGameResponse.newBuilder(result.matchNewGameResponse_).mergeFrom(value).buildPartial();
        } else {
          result.matchNewGameResponse_ = value;
        }
        result.hasMatchNewGameResponse = true;
        return this;
      }
      public Builder clearMatchNewGameResponse() {
        result.hasMatchNewGameResponse = false;
        result.matchNewGameResponse_ = com.randioo.shanghaimajiang_server.protocol.Match.MatchNewGameResponse.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.shanghaimajiang_server.protocol.MatchJoinGameResponse MatchJoinGameResponse = 6;
      public boolean hasMatchJoinGameResponse() {
        return result.hasMatchJoinGameResponse();
      }
      public com.randioo.shanghaimajiang_server.protocol.Match.MatchJoinGameResponse getMatchJoinGameResponse() {
        return result.getMatchJoinGameResponse();
      }
      public Builder setMatchJoinGameResponse(com.randioo.shanghaimajiang_server.protocol.Match.MatchJoinGameResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasMatchJoinGameResponse = true;
        result.matchJoinGameResponse_ = value;
        return this;
      }
      public Builder setMatchJoinGameResponse(com.randioo.shanghaimajiang_server.protocol.Match.MatchJoinGameResponse.Builder builderForValue) {
        result.hasMatchJoinGameResponse = true;
        result.matchJoinGameResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeMatchJoinGameResponse(com.randioo.shanghaimajiang_server.protocol.Match.MatchJoinGameResponse value) {
        if (result.hasMatchJoinGameResponse() &&
            result.matchJoinGameResponse_ != com.randioo.shanghaimajiang_server.protocol.Match.MatchJoinGameResponse.getDefaultInstance()) {
          result.matchJoinGameResponse_ =
            com.randioo.shanghaimajiang_server.protocol.Match.MatchJoinGameResponse.newBuilder(result.matchJoinGameResponse_).mergeFrom(value).buildPartial();
        } else {
          result.matchJoinGameResponse_ = value;
        }
        result.hasMatchJoinGameResponse = true;
        return this;
      }
      public Builder clearMatchJoinGameResponse() {
        result.hasMatchJoinGameResponse = false;
        result.matchJoinGameResponse_ = com.randioo.shanghaimajiang_server.protocol.Match.MatchJoinGameResponse.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.shanghaimajiang_server.protocol.FightCmdResponse FightCmdResponse = 7;
      public boolean hasFightCmdResponse() {
        return result.hasFightCmdResponse();
      }
      public com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse getFightCmdResponse() {
        return result.getFightCmdResponse();
      }
      public Builder setFightCmdResponse(com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasFightCmdResponse = true;
        result.fightCmdResponse_ = value;
        return this;
      }
      public Builder setFightCmdResponse(com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse.Builder builderForValue) {
        result.hasFightCmdResponse = true;
        result.fightCmdResponse_ = builderForValue.build();
        return this;
      }
      public Builder mergeFightCmdResponse(com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse value) {
        if (result.hasFightCmdResponse() &&
            result.fightCmdResponse_ != com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse.getDefaultInstance()) {
          result.fightCmdResponse_ =
            com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse.newBuilder(result.fightCmdResponse_).mergeFrom(value).buildPartial();
        } else {
          result.fightCmdResponse_ = value;
        }
        result.hasFightCmdResponse = true;
        return this;
      }
      public Builder clearFightCmdResponse() {
        result.hasFightCmdResponse = false;
        result.fightCmdResponse_ = com.randioo.shanghaimajiang_server.protocol.Fight.FightCmdResponse.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.shanghaimajiang_server.protocol.SCFightWait SCFightWait = 8;
      public boolean hasSCFightWait() {
        return result.hasSCFightWait();
      }
      public com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait getSCFightWait() {
        return result.getSCFightWait();
      }
      public Builder setSCFightWait(com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasSCFightWait = true;
        result.sCFightWait_ = value;
        return this;
      }
      public Builder setSCFightWait(com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait.Builder builderForValue) {
        result.hasSCFightWait = true;
        result.sCFightWait_ = builderForValue.build();
        return this;
      }
      public Builder mergeSCFightWait(com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait value) {
        if (result.hasSCFightWait() &&
            result.sCFightWait_ != com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait.getDefaultInstance()) {
          result.sCFightWait_ =
            com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait.newBuilder(result.sCFightWait_).mergeFrom(value).buildPartial();
        } else {
          result.sCFightWait_ = value;
        }
        result.hasSCFightWait = true;
        return this;
      }
      public Builder clearSCFightWait() {
        result.hasSCFightWait = false;
        result.sCFightWait_ = com.randioo.shanghaimajiang_server.protocol.Fight.SCFightWait.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.shanghaimajiang_server.protocol.SC)
    }
    
    static {
      defaultInstance = new SC(true);
      com.randioo.shanghaimajiang_server.protocol.ServerMessage.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.shanghaimajiang_server.protocol.SC)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_shanghaimajiang_server_protocol_SC_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_shanghaimajiang_server_protocol_SC_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ServerMessage.proto\022+com.randioo.shang" +
      "haimajiang_server.protocol\032\013Login.proto\032" +
      "\nRole.proto\032\013Match.proto\032\013Fight.proto\"\210\006" +
      "\n\002SC\022i\n\031LoginCheckAccountResponse\030\001 \001(\0132" +
      "F.com.randioo.shanghaimajiang_server.pro" +
      "tocol.LoginCheckAccountResponse\022e\n\027Login" +
      "CreateRoleResponse\030\002 \001(\0132D.com.randioo.s" +
      "hanghaimajiang_server.protocol.LoginCrea" +
      "teRoleResponse\022g\n\030LoginGetRoleDataRespon" +
      "se\030\003 \001(\0132E.com.randioo.shanghaimajiang_s",
      "erver.protocol.LoginGetRoleDataResponse\022" +
      "[\n\022RoleRenameResponse\030\004 \001(\0132?.com.randio" +
      "o.shanghaimajiang_server.protocol.RoleRe" +
      "nameResponse\022_\n\024MatchNewGameResponse\030\005 \001" +
      "(\0132A.com.randioo.shanghaimajiang_server." +
      "protocol.MatchNewGameResponse\022a\n\025MatchJo" +
      "inGameResponse\030\006 \001(\0132B.com.randioo.shang" +
      "haimajiang_server.protocol.MatchJoinGame" +
      "Response\022W\n\020FightCmdResponse\030\007 \001(\0132=.com" +
      ".randioo.shanghaimajiang_server.protocol",
      ".FightCmdResponse\022M\n\013SCFightWait\030\010 \001(\01328" +
      ".com.randioo.shanghaimajiang_server.prot" +
      "ocol.SCFightWait"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_shanghaimajiang_server_protocol_SC_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_shanghaimajiang_server_protocol_SC_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_shanghaimajiang_server_protocol_SC_descriptor,
              new java.lang.String[] { "LoginCheckAccountResponse", "LoginCreateRoleResponse", "LoginGetRoleDataResponse", "RoleRenameResponse", "MatchNewGameResponse", "MatchJoinGameResponse", "FightCmdResponse", "SCFightWait", },
              com.randioo.shanghaimajiang_server.protocol.ServerMessage.SC.class,
              com.randioo.shanghaimajiang_server.protocol.ServerMessage.SC.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.shanghaimajiang_server.protocol.Login.getDescriptor(),
          com.randioo.shanghaimajiang_server.protocol.Role.getDescriptor(),
          com.randioo.shanghaimajiang_server.protocol.Match.getDescriptor(),
          com.randioo.shanghaimajiang_server.protocol.Fight.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
